name: Build and Deploy Release Version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  result_build:
    name: Build Every Application and Push to DockerHub with Version Tags.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: DockerHub Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Result Docker Image With Version
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/result:${{ env.RELEASE_VERSION }} -t ${{ secrets.DOCKER_USERNAME }}/result:latest  ./result

      - name: Push Result to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/result

      - name: Build Vote Docker Image With Version
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vote:${{ env.RELEASE_VERSION }} -t ${{ secrets.DOCKER_USERNAME }}/vote:latest ./vote

      - name: Push Vote to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vote

      - name: Build Worker Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/worker:${{ env.RELEASE_VERSION }} -t ${{ secrets.DOCKER_USERNAME }}/worker:latest ./worker

      - name: Push Worker to Docker Hub With Version
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/worker

      - name: Connecting to DigitalOcean Droplet by SSH and Running Docker-Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: export VERSION=${{ env.RELEASE_VERSION }} && cd proyecto-ucc-ingsoft3/ && git checkout develop && git pull origin develop && docker-compose down && docker-compose up -d

      - name: Run Integration Tests with CodeceptJS
        run: |
          cd integration/ && npm install && npm run codeceptjs
