name: Deploy

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: imagename

jobs:

  pushToDORegistry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: git clone https://github.com/lmurature/proyecto-ucc-ingsoft3.git && cd proyecto-ucc-ingsoft3/ && docker-compose up -d
