name: Deploy

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: imagename

jobs:

  deployToDO:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: cd proyecto-ucc-ingsoft3/ && git pull origin master && docker-compose up -d
