name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shipping_service_job:
    runs-on: ubuntu-latest
    name: "Job to build shipping_service"
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        
      - name: Get dependencies
        run: |
          cd shippingservice/
          go mod download
          
      - name: Build
        run: |
          cd shippingservice/
          go build -v .

      - name: Test
        run: |
          cd shippingservice/
          go test -v .
