name: Vote

on:
  push:
    branches: [ master ]

jobs:
  result_build:
    name: Build and Push Vote
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          file: ./vote/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lmurature/vote
          tag_with_ref: true


