name: Worker

on:
  push:
    branches: [ master ]

jobs:
  result_build:
    name: Build and Push Worker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: ./worker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lmurature/worker
          tag_with_ref: true


