name: Worker

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  result_build:
    name: Build and Push Worker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: DockerHub Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: |
          docker build -t worker ./worker

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/worker

      #- name: Build and Push to Docker Hub
      #  uses: docker/build-push-action@v1
      #  with:
      #    path: ./worker
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      #    repository: lmurature/worker
      #    tag_with_ref: true
